// Host-side memory-safety tests for the OTLP metrics encoder.
//   pio test -e native_otel
//
// Why this exists: the export task runs while the machine pulls a shot. The
// in-shot batch is the heaviest payload (every gauge x MAX_GAUGE_POINTS points,
// each with attributes + an exemplar). These tests prove two things on the host
// so we never find out the hard way on the device:
//   1. The worst-case batch encodes within OpenTelemetryPlugin::BUFFER_SIZE.
//   2. The encoder NEVER writes past the buffer it is given, for ANY buffer
//      size - so a too-small buffer drops/truncates telemetry but can never
//      corrupt memory or reboot the board mid-shot.
//
// Direct-include the implementation (native harness, same pattern as
// test_autotune_simc). otlp.pb.h is generated by the nanopb builder into the
// build dir, which the env adds to the include path.

#include <unity.h>

#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

#include "OtlpEncoder.cpp"

#include <pb_decode.h>

using namespace otel;

// MUST stay in sync with OpenTelemetryPlugin. Kept here (rather than including
// the plugin header, which drags in Arduino/FreeRTOS) so the host build is
// self-contained. If you change either constant in the plugin, change it here.
static constexpr size_t FW_BUFFER_SIZE = 40960;   // OpenTelemetryPlugin::BUFFER_SIZE
static constexpr size_t FW_MAX_GAUGE_POINTS = 20; // OpenTelemetryPlugin::MAX_GAUGE_POINTS

// Resource attributes sized at/near the otlp.options maxima, matching what the
// firmware emits (service.name/instance.id/version, host.type, grinder.model).
static std::vector<Attribute> worstCaseResourceAttrs() {
    return {
        Attribute::str("service.name", "gaggimate"),
        Attribute::str("service.instance.id", "AA:BB:CC:DD:EE:FF"),
        Attribute::str("service.version", "v1.234.5-abcdef0-dirty-longest"),
        Attribute::str("host.type", "LilyGo-T-RGB-ESP32S3-N16R8"),
        Attribute::str("coffee.grinder.model", "Some Very Long Grinder Model Name 48c"),
    };
}

// Build the heaviest realistic metric set: every gauge carries the full point
// batch, every point is in-shot (3 attributes + exemplar), plus the cumulative
// sums. Mirrors OpenTelemetryPlugin::exportMetrics worst case.
static std::vector<MetricSeries> worstCaseMetrics(size_t pointsPerGauge) {
    const char *gauges[][2] = {
        {"coffee.boiler.temperature", "Cel"}, {"coffee.boiler.target_temperature", "Cel"},
        {"coffee.boiler.pressure", "bar"},    {"coffee.pump.flow", "ml/s"},
        {"coffee.pump.puck_flow", "ml/s"},    {"coffee.pump.puck_resistance", ""},
        {"coffee.scale.weight", "g"},
    };
    // 32-hex shot id (16-byte trace id) - the longest attribute value.
    const std::string shotId(32, 'f');
    const char *phaseName = "preinfusion-ramp-stage"; // 22 chars, near the 24 cap

    std::vector<MetricSeries> metrics;
    for (auto &g : gauges) {
        MetricSeries s;
        s.name = g[0];
        s.unit = g[1];
        s.kind = MetricSeries::GAUGE;
        for (size_t i = 0; i < pointsPerGauge; i++) {
            DataPoint dp;
            dp.timeNanos = 1700000000000000000ULL + i * 500000000ULL;
            dp.value = 93.456 + i;
            dp.attributes.push_back(Attribute::str("coffee.shot.id", String(shotId)));
            dp.attributes.push_back(Attribute::dbl("coffee.grind.level", 12.5));
            dp.attributes.push_back(Attribute::str("coffee.phase.name", phaseName));
            dp.hasExemplar = true;
            for (int b = 0; b < 16; b++)
                dp.traceId[b] = 0xAB;
            for (int b = 0; b < 8; b++)
                dp.spanId[b] = 0xCD;
            s.points.push_back(std::move(dp));
        }
        metrics.push_back(std::move(s));
    }

    const char *sums[][2] = {
        {"coffee.shots.total", "{shot}"},
        {"coffee.brew.duration.total", "s"},
        {"coffee.water.total", "ml"},
        {"coffee.wifi.disconnects.total", "{event}"},
        {"coffee.bluetooth.disconnects.total", "{event}"},
    };
    for (auto &c : sums) {
        MetricSeries s;
        s.name = c[0];
        s.unit = c[1];
        s.kind = MetricSeries::SUM;
        s.monotonic = true;
        DataPoint dp;
        dp.timeNanos = 1700000010000000000ULL;
        dp.value = 1234.0;
        s.points.push_back(std::move(dp));
        metrics.push_back(std::move(s));
    }
    return metrics;
}

void setUp() {}
void tearDown() {}

// The nanopb request structs must stay under the 64KB-per-message cap. This is
// also enforced at firmware compile time (static_assert in OtlpEncoder.cpp);
// re-checked here so the host test reports the actual headroom.
static void test_structs_within_nanopb_limit() {
    printf("[otel] sizeof otlp_ScopeMetrics                 = %zu bytes\n", sizeof(otlp_ScopeMetrics));
    printf("[otel] sizeof otlp_ResourceMetrics              = %zu bytes\n", sizeof(otlp_ResourceMetrics));
    printf("[otel] sizeof otlp_ExportMetricsServiceRequest  = %zu bytes\n", sizeof(otlp_ExportMetricsServiceRequest));
    TEST_ASSERT_LESS_THAN_size_t(64u * 1024u, sizeof(otlp_ScopeMetrics));
    TEST_ASSERT_LESS_THAN_size_t(64u * 1024u, sizeof(otlp_ResourceMetrics));
    TEST_ASSERT_LESS_THAN_size_t(64u * 1024u, sizeof(otlp_ExportMetricsServiceRequest));
}

// The worst-case in-shot batch must fit the firmware's export buffer with room
// to spare. If this fails, raise BUFFER_SIZE or lower MAX_GAUGE_POINTS.
static void test_worst_case_batch_fits_buffer() {
    std::vector<uint8_t> buf(FW_BUFFER_SIZE);
    const std::vector<Attribute> res = worstCaseResourceAttrs();
    const std::vector<MetricSeries> metrics = worstCaseMetrics(FW_MAX_GAUGE_POINTS);

    const size_t len = OtlpEncoder::encodeMetrics(res, "gaggimate", "v1.234.5-abcdef0", metrics,
                                                  1700000000000000000ULL, buf.data(), buf.size());

    printf("[otel] worst-case in-shot batch encoded         = %zu / %zu bytes (%.0f%% of buffer)\n", len, FW_BUFFER_SIZE,
           100.0 * len / FW_BUFFER_SIZE);
    TEST_ASSERT_GREATER_THAN_size_t(0, len);
    TEST_ASSERT_LESS_OR_EQUAL_size_t(FW_BUFFER_SIZE, len);
}

// Reads a base-128 varint. Returns bytes consumed, or 0 if truncated.
static size_t readVarint(const uint8_t *p, size_t avail, uint64_t *out) {
    uint64_t v = 0;
    int shift = 0;
    for (size_t i = 0; i < avail; i++) {
        const uint8_t b = p[i];
        v |= static_cast<uint64_t>(b & 0x7F) << shift;
        if (!(b & 0x80)) {
            *out = v;
            return i + 1;
        }
        shift += 7;
    }
    return 0;
}

// All MAX_GAUGE_POINTS points must survive the chunked encode (the batch is
// split across several ResourceMetrics, then concatenated into one body). The
// firmware never decodes, and the shared request struct only holds one
// ResourceMetrics, so walk the top-level stream by hand: each chunk is a
// length-delimited field 1 (tag 0x0A), decoded into the per-chunk struct. Proves
// no point is dropped and the cumulative sums appear exactly once.
static void test_all_points_survive_chunking() {
    std::vector<uint8_t> buf(FW_BUFFER_SIZE);
    const std::vector<Attribute> res = worstCaseResourceAttrs();
    const std::vector<MetricSeries> metrics = worstCaseMetrics(FW_MAX_GAUGE_POINTS);
    const size_t len = OtlpEncoder::encodeMetrics(res, "gaggimate", "v1", metrics, 1700000000000000000ULL, buf.data(),
                                                  buf.size());
    TEST_ASSERT_GREATER_THAN_size_t(0, len);

    auto *rm = static_cast<otlp_ResourceMetrics *>(malloc(sizeof(otlp_ResourceMetrics)));
    TEST_ASSERT_NOT_NULL(rm);

    size_t weightPoints = 0;
    size_t sumSeries = 0;
    size_t chunks = 0;
    size_t off = 0;
    while (off < len) {
        TEST_ASSERT_EQUAL_UINT8_MESSAGE(0x0A, buf[off], "expected field-1 LEN tag at chunk boundary");
        off++;
        uint64_t msgLen = 0;
        const size_t vn = readVarint(buf.data() + off, len - off, &msgLen);
        TEST_ASSERT_GREATER_THAN_size_t(0, vn);
        off += vn;
        TEST_ASSERT_LESS_OR_EQUAL_size_t(len, off + msgLen);

        memset(rm, 0, sizeof(*rm));
        pb_istream_t is = pb_istream_from_buffer(buf.data() + off, msgLen);
        TEST_ASSERT_TRUE_MESSAGE(pb_decode(&is, &otlp_ResourceMetrics_msg, rm), "ResourceMetrics decode failed");
        for (pb_size_t sm = 0; sm < rm->scope_metrics_count; sm++) {
            const otlp_ScopeMetrics &s = rm->scope_metrics[sm];
            for (pb_size_t m = 0; m < s.metrics_count; m++) {
                const otlp_Metric &met = s.metrics[m];
                if (met.which_data == otlp_Metric_gauge_tag && std::string(met.name) == "coffee.scale.weight")
                    weightPoints += met.data.gauge.data_points_count;
                if (met.which_data == otlp_Metric_sum_tag)
                    sumSeries++;
            }
        }
        off += msgLen;
        chunks++;
    }
    free(rm);

    printf("[otel] chunks=%zu, weight points=%zu (expected %zu), sum series=%zu (expected 5)\n", chunks, weightPoints,
           FW_MAX_GAUGE_POINTS, sumSeries);
    TEST_ASSERT_GREATER_THAN_size_t(1, chunks); // 20 points / 8 per chunk -> 3 chunks
    TEST_ASSERT_EQUAL_size_t(FW_MAX_GAUGE_POINTS, weightPoints);
    // Sums must appear exactly once across all chunks (not duplicated per chunk).
    TEST_ASSERT_EQUAL_size_t(5, sumSeries);
}

// The anti-brick property: for every buffer size from tiny to oversized, the
// encoder must (a) never write past the buffer and (b) never report more bytes
// than the buffer holds. A guard region after the buffer is checked for
// tampering. This is the guarantee that a pathological batch can drop telemetry
// but cannot corrupt memory while the machine is mid-shot.
static void test_encoder_never_overflows_any_buffer() {
    const std::vector<Attribute> res = worstCaseResourceAttrs();
    const std::vector<MetricSeries> metrics = worstCaseMetrics(FW_MAX_GAUGE_POINTS);

    constexpr size_t GUARD = 64;
    constexpr uint8_t CANARY = 0xA5;

    for (size_t cap = 0; cap <= FW_BUFFER_SIZE + 1024; cap += 137) {
        std::vector<uint8_t> mem(cap + GUARD, CANARY);
        const size_t len =
            OtlpEncoder::encodeMetrics(res, "gaggimate", "v1", metrics, 1700000000000000000ULL, mem.data(), cap);

        TEST_ASSERT_LESS_OR_EQUAL_size_t(cap, len);
        for (size_t g = 0; g < GUARD; g++) {
            if (mem[cap + g] != CANARY) {
                char msg[96];
                snprintf(msg, sizeof(msg), "buffer overflow: guard byte %zu clobbered at cap=%zu", g, cap);
                TEST_FAIL_MESSAGE(msg);
            }
        }
    }
}

// Shot ratings are emitted as a span on the shot's own trace, using ids read
// back from a notes file on flash. A malformed/absent id must be rejected
// outright rather than half-parsed into a span pointing at a random trace.
static void test_hex_to_bytes_rejects_bad_ids() {
    uint8_t out[16];
    memset(out, 0xAA, sizeof(out));

    const char *valid = "0123456789abcdefFEDCBA9876543210";
    TEST_ASSERT_TRUE(hexToBytes(valid, strlen(valid), out, 16));
    TEST_ASSERT_EQUAL_UINT8(0x01, out[0]);
    TEST_ASSERT_EQUAL_UINT8(0xEF, out[7]);
    TEST_ASSERT_EQUAL_UINT8(0x10, out[15]);

    uint8_t span[8];
    const char *validSpan = "0011223344556677";
    TEST_ASSERT_TRUE(hexToBytes(validSpan, strlen(validSpan), span, 8));
    TEST_ASSERT_EQUAL_UINT8(0x77, span[7]);

    // Rejected inputs must leave the output buffer untouched.
    memset(out, 0xAA, sizeof(out));
    TEST_ASSERT_FALSE(hexToBytes("", 0, out, 16));                                  // absent id
    TEST_ASSERT_FALSE(hexToBytes("0123", 4, out, 16));                              // too short
    TEST_ASSERT_FALSE(hexToBytes(nullptr, 32, out, 16));                            // no notes field
    TEST_ASSERT_FALSE(hexToBytes("0123456789abcdefFEDCBA987654321", 31, out, 16));  // odd length
    TEST_ASSERT_FALSE(hexToBytes("0123456789abcdefFEDCBA98765432zz", 32, out, 16)); // non-hex
    for (size_t i = 0; i < sizeof(out); i++) {
        TEST_ASSERT_EQUAL_UINT8(0xAA, out[i]);
    }
}

int main(int, char **) {
    UNITY_BEGIN();
    RUN_TEST(test_hex_to_bytes_rejects_bad_ids);
    RUN_TEST(test_structs_within_nanopb_limit);
    RUN_TEST(test_worst_case_batch_fits_buffer);
    RUN_TEST(test_all_points_survive_chunking);
    RUN_TEST(test_encoder_never_overflows_any_buffer);
    return UNITY_END();
}
